export const CREATE_REMINDER = 'CREATE_REMINDER'
export const UPDATE_REMINDER = 'UPDATE_REMINDER'
export const REMOVE_REMINDER = 'REMOVE_REMINDER'
export const CLEAR_REMINDERS_ON_DAY = 'CLEAR_REMINDERS_ON_DAY'
